# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'learn_code' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for learn_code
  pod 'IQKeyboardManager' 
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseDatabase'
  pod 'FirebaseStorage'
  pod 'FirebaseCrashlytics'
  pod 'FirebaseMessaging'
  pod 'SDWebImage'
  pod 'ReachabilitySwift'


  
  
  target 'learn_codeTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'learn_codeUITests' do
    # Pods for testing
  end
  
end
